../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:1001 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:1002 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:1003 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:1004 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2001 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2002 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2003 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2004 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2005 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2006 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2007 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:2008 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3001 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3002 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3003 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3004 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3005 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3006 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3007 &
../../veil_switch.pyc fat-tree-k2.adlist fat-tree-k2.vid localhost:3008 &
../../traffic-gen.pyc fat-tree-k2.vid fat-tree-k2.test1.workload localhost:3001 &
../../traffic-gen.pyc fat-tree-k2.vid fat-tree-k2.test1.workload localhost:3005
