../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8001 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8002 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8003 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8004 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8005 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8006 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8007 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8008 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8009 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8010 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8011 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8012 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8013 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8014 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8015 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8016 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8017 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8018 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8019 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8020 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8021 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8022 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8023 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8024 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8025 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8026 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8027 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8028 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8029 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8030 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8031 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8032 &
../../veil_switch.pyc isp-level3.adlist isp-level3.vid localhost:8033
